language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - PHP_CURRENT='5.6'

before_script:
  - composer selfupdate

script:
  - make phpunit
  - if [ $(phpenv version-name) = $PHP_CURRENT ]; then make phpcs phpmd bugfree && make test-upload; fi
  - make clean

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

notifications:
  webhooks:
    urls:
      - http://derricks.io/repositories/buildhook/
    on_success: always
    on_failure: always
    on_start: true
